### ISSUE TITLE
Cherry-pick dart PR 1407

### ISSUE THREAD

**Issue by peci1** [gazebo-forks/dart#17]
https://github.com/dartsim/dart/pull/1407

Without this PR, it seems that [`<joint><axis><limit><velocity>`](http://sdformat.org/spec?ver=1.6&elem=joint#limit_velocity) is ignored, although the parsed data are passed to DART:

https://github.com/ignitionrobotics/ign-physics/blob/56a04fe204afa77e6a16d84b27ec289823eb330a/dartsim/src/SDFFeatures.cc#L116-L134

So creating a JointPositionController in ign-gazebo creates unusable controllers, as they use unlimited velocity if enough force is allowed (yes, if the joint was modeled super precisely, including all daping/internal friction etc., this artificial limit would not be needed, but being able to set this limit simplifies the creation of models a lot).

This did not show in any of ign-gazebo tests as none of them actually set the velocity limits and check them.

**Comment by scpeters** [comment]
see https://github.com/ignition-forks/dart/pull/19
